### ISSUE TITLE
babelHelpers._typeof is not a function

### ISSUE THREAD

**Issue by yairEO** [rollup/babel-preset-es2015-rollup#1]
it happens when I use this setup:

```
gulp.src('js/dist/app.js', {read: false})
    //.pipe(rollup({format: 'amd'}))
    .pipe(rollup({
        format : 'umd',
        moduleId: config.namespace,
        sourceMap: true,
        plugins: [
            babelRollup({
                presets: ['es2015-rollup'],
                exclude: 'node_modules/**'
            })
          ]
    }))
    .pipe(sourcemaps.write("."))
    .pipe(concat( config.namespace + '.js'))

    .pipe(gulp.dest('../js/'))
```

**Comment by Rich-Harris** [comment]
That's odd. Could you share a repo with a minimal reproduction of the issue so I can investigate? Thanks

**Comment by yairEO** [comment]
https://github.com/yairEO/ToDo

see `bundleJS` task in the gulpfile (everything is in the `/BUILD` folder)

I just can't make it work! tried to update all my packages and their dependencies, but still...

**Comment by yairEO** [comment]
I would guess it has something to do with the line of code in the `index.js` of your package:

```
plugins.push( require( 'babel-plugin-external-helpers-2' ) );
```

Maybe it doesn't actually put those helper function in the output rollup code, so when it calls a helper function, it is undefined? I lack the sufficient knowledge of tracing the problem...NPM packages are a maze of dependencies.

**Comment by yairEO** [comment]
### Update

I deleted all my packages and ran `npm install` again, and now things work. Sorry to have bothered you, it was a very peculiar case.

**Comment by Victorystick** [comment]
@yairEO Glad to hear it worked out.
