### ISSUE TITLE
please update modify-babel-preset to 3.1.0

### ISSUE THREAD

**Issue by thisconnect** [rollup/babel-preset-es2015-rollup#18]
https://github.com/developit/modify-babel-preset/releases

https://david-dm.org/rollup/babel-preset-es2015-rollup

**Comment by sorgloomer** [comment]
Unfortunately it seems this repo isn't maintained anymore. But the es2015 preset allows switching off module transpilation, so this babel config should be just fine:

```
 {
  "presets": [
    ["es2015", { "modules": false }]
  ],
  "plugins": [
    "external-helpers"
  ]
}
```

**Comment by thisconnect** [comment]
Oh thanks. I guess I try Bublé, I thought that it wouldn't support JSX (by reading https://www.npmjs.com/package/rollup-plugin-buble and https://www.npmjs.com/package/buble)

But there is a JSX section https://buble.surge.sh/guide/#jsx

Else I try your suggestion. Thanks @sorgloomer

**Comment by travi** [comment]
with the latest babel release, this is a [bigger problem](https://github.com/babel/babel/issues/4985). seeing that it is unlikely to be resolved soon, i will update to use `babel-preset-es2015` directly, as suggested above, but the convenience of this preset was nice.

**Comment by Rich-Harris** [comment]
I've removed modify-babel-preset in version 3 (it was causing problems in npm2) so I'll close this issue.

**Comment by travi** [comment]
thanks for getting this rolled out. it seems to have resolved the issue that i was seeing

**Comment by lzxb** [comment]
ok，Problem has been solved
