### ISSUE TITLE
Github releases don't match npm

### ISSUE THREAD

**Issue by notdotscott** [rollup/babel-preset-es2015-rollup#6]
Hi,

Just wondering why npm says the latest release is 1.1.1 but there's no matching Github release? Also the package.json in master is still on 1.1.0.

I'm having issues with builds on my server and wanted to rule this out as a cause (currently targeting ^1.1.1 as a dependency).

Thanks!

**Comment by Rich-Harris** [comment]
Sorry for the non-response. Short answer is I don't know, but v3.0.0 just landed so hopefully it's no longer an issue!
